### ISSUE TITLE
requirehub-web gitHubUrl

### ISSUE THREAD

**Issue by mxfactorial** [mxfactorial/requirehub-web#10]
Steps:
1. Navigate to `/` in browser to display [gitHubUrl](https://docs.google.com/drawings/d/1DXZAmVAMQxjVYw88M7UjtJm6g_veTb0VeEZdhoMpPco/edit?usp=sharing) at top of screen.
2. Select project-dropdown-menu-button with default "server" copy to display "client" option in project-dropdown-menu.
3. Select "client" option in project-dropdown-menu to display `https://github.com/mxfactorial/requirehub-web` url in project-dropdown-menu-box.
4. Select `https://github.com/mxfactorial/requirehub-web` url in project-dropdown-menu-box.

Expected:
Browser navigates to `https://github.com/mxfactorial/requirehub-web` url in new window (target="_blank").

**Comment by enesTufekci** [comment]
#15

**Comment by mxfactorial** [comment]
Closed by https://github.com/mxfactorial/requirehub-web/pull/15
