### ISSUE TITLE
requirehub gitHubUrl

### ISSUE THREAD

**Issue by mxfactorial** [mxfactorial/requirehub-web#11]
Steps:
1. In [gitHubUrl](https://docs.google.com/drawings/d/1DXZAmVAMQxjVYw88M7UjtJm6g_veTb0VeEZdhoMpPco/edit?usp=sharing) at top of screen, switch to "client" option to display `https://github.com/mxfactorial/requirehub-web` url.
2. Switch gitHubUrl back to "server" copy to display `https://github.com/mxfactorial/requirehub` url
3. Select `https://github.com/mxfactorial/requirehub` url in project-dropdown-menu-box.

Expected:
Browser navigates to `https://github.com/mxfactorial/requirehub` url in new window (target="_blank").

**Comment by enesTufekci** [comment]
#15

**Comment by mxfactorial** [comment]
Closed by https://github.com/mxfactorial/requirehub-web/pull/15
