### ISSUE TITLE
homeScreen

### ISSUE THREAD

**Issue by mxfactorial** [mxfactorial/requirehub-web#2]
Steps:
1. Navigate to / in browser.

Expected:
1. [empty home](https://docs.google.com/drawings/d/17YLtS5I4nekO4FIc8HAJi1I4uVpE1ecwWmRMMskj_kQ/edit?usp=sharing) displays:
2. requirementPlaceholder
3. addRequirementButton

**Comment by enesTufekci** [comment]
__Estimation__: 1 hour.

Before this task i will implement [router](https://github.com/ReactTraining/react-router) and [enzyme](https://github.com/airbnb/enzyme).

**Comment by enesTufekci** [comment]
[This PR](https://github.com/mxfactorial/requirehub-web/pull/5) covers this task.

**Comment by mxfactorial** [comment]
Closed by https://github.com/mxfactorial/requirehub-web/pull/6
