### ISSUE TITLE
Non empty home

### ISSUE THREAD

**Issue by mxfactorial** [mxfactorial/requirehub-web#4]
Steps:
1. Insert title, steps, and expected on addRequirement
2. Select saveButton.

Expected:
1. [Non empty home](https://docs.google.com/drawings/d/1GMQ04TG-OcyVNvUnqmHQ55i71Fat1JcnLyImH3JE0JU/edit?usp=sharing) displays:
2. requirementTitleComponent displays requirement title
3. keyComponent
4. addRequirementButton
5. extensibility alert: requirement list component will later provide for rearranging sequence of requirements through UI action

**Comment by enesTufekci** [comment]
__Estimation__: 45 mins.

**Comment by mxfactorial** [comment]
https://github.com/mxfactorial/requirehub-web/pull/6 excluded the keyComponent (renamed to requirement-key in mock). Please add to close this issue.

**Comment by enesTufekci** [comment]
Please check #16

**Comment by mxfactorial** [comment]
Closed by https://github.com/mxfactorial/requirehub-web/pull/16
