### ISSUE TITLE
gitHubUrl displays at top of home

### ISSUE THREAD

**Issue by mxfactorial** [mxfactorial/requirehub-web#9]
Steps:
1. Navigate to / in browser.

Expected:
1. home displays [gitHubUrl](https://docs.google.com/drawings/d/1DXZAmVAMQxjVYw88M7UjtJm6g_veTb0VeEZdhoMpPco/edit?usp=sharing) at top of screen
2. "< R > on GitHub" copy displays using [requirehub-logo.png](https://drive.google.com/open?id=1ZenSASXdziPXRZSEOuqttOcynI_4G1RR) and [github-logo.png](https://drive.google.com/open?id=16YNTdae6ZUc5ExZDLhq-e_HnlC4O1q0x)
3. project-dropdown-menu-box with project-dropdown-menu-button
4. project-dropdown-menu-button displays default "server" copy
5. project-dropdown-menu-box displays default `https://github.com/mxfactorial/requirehub` url
6. selecting url project-dropdown-menu-box navigates to url in new window (target="_blank")

**Comment by enesTufekci** [comment]
#15

**Comment by mxfactorial** [comment]
Observed:
1. Pass
2. Fail:  ![issue_15_bug_01](https://user-images.githubusercontent.com/12200465/37190310-f66a0a98-230d-11e8-8f8b-062ef9b2dc43.png)
The "< R > On GitHub" copy displays (vowel capitalized; not capital expected). Also, increase proportionality of "on" copy size to logos, and reduce difference in logo sizes.
3. Fail: [input-group](https://v4-alpha.getbootstrap.com/components/input-group/#buttons-with-dropdowns) intended, but materialcss may not offer the solution. Needn't lock this project into any single framework. Experiment with the [input-group](http://rosskevin.github.io/bootstrap-material-design/components/input-group/#buttons-with-dropdowns) in bootstrap-material-design.
4. Pass
5. Pass
6. Fail: selecting project-dropdown-menu-box, rather than url, navigates to url in new window. if whole project-dropdown-menu-box is linked, then user cannot copy link to clipboard in addition to click-navigation.

**Comment by enesTufekci** [comment]
You meant __project-dropdown-menu-button__ "6. Fail: selecting project-dropdown-menu-box" here right?

------

### Which event should occur when `project-dropdown-menu-box` is clicked?
__a.__ browser should navigate to the url (target=_blank)
__b.__ browser copies the url to clipboard
__c.__ does nothing, lets user select the text.

**Comment by mxfactorial** [comment]
**project-dropdown-menu-box** intended. The project-dropdown-menu-button only switches the content of the project-dropdown-menu-box between server and client urls:

When project-dropdown-menu-button copy = "server", project-dropdown-menu-box displays https://github.com/mxfactorial/requirehub.
When project-dropdown-menu-button copy = "client", project-dropdown-menu-box displays https://github.com/mxfactorial/requirehub-web.

> Which event should occur when project-dropdown-menu-box is clicked?  

a & c. Attach listener to inner text instead of surrounding box. Launch new browser to link when text directly clicked, but allow user to select internal text to manually populate their clipboard. May try using a form and [lock defaulted input](https://stackoverflow.com/a/34006497).

Also, the linked requirehub-logo.png in the initial draft of this case points to a logo with a white background (requirement failure). Please switch to version with [transparent background](https://drive.google.com/file/d/1UHQ3ePbNq_t9Y_L1KZoQ9r1j1EI9sQa3/view?usp=sharing).

**Comment by mxfactorial** [comment]
Admittedly, the [gitHubUrl](https://docs.google.com/drawings/d/1DXZAmVAMQxjVYw88M7UjtJm6g_veTb0VeEZdhoMpPco/edit?usp=sharing) mock doesn't indicate size and position relative to the requirement-placeholder. Anchoring width of gitHubUrl to width of requirement-placeholder causes an abnormal gap between "on" and logos. 
Updated [emptyHome](https://docs.google.com/drawings/d/17YLtS5I4nekO4FIc8HAJi1I4uVpE1ecwWmRMMskj_kQ/edit?usp=sharing) with gitHubUrl size and position.
Also, as documented in https://github.com/mxfactorial/requirehub-web/issues/10, please disable navigation to url in new window (target="_blank") after selecting "Client" or "Server" in project-dropdown-menu-button. Selecting "Client" or "Server" from within project-dropdown-menu-button only switches urls in project-dropdown-menu-box. Only selecting urls inside project-dropdown-menu-box navigates to url in new window (target="_blank").

**Comment by enesTufekci** [comment]
updated

**Comment by mxfactorial** [comment]
Almost there. 50% smaller, please.

**Comment by enesTufekci** [comment]
You mean logos right?

**Comment by mxfactorial** [comment]
Closed by https://github.com/mxfactorial/requirehub-web/pull/15
